export const WAREHOUSE_CATEGORY_SUGGESTIONS = [
  'Aceites',
  'Azúcares',
  'Bebidas',
  'Café',
  'Carnes',
  'Condimentos',
  'Embutidos',
  'Empaques',
  'Endulzantes',
  'Especias',
  'Frutas',
  'Granos',
  'Harinas',
  'Huevos',
  'Lácteos',
  'Mariscos',
  'Panadería',
  'Pastas',
  'Proteínas',
  'Salsas',
  'Snacks',
  'Tubérculos',
  'Vegetales',
  'Otros',
] as const
