services:
  warocol:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - env_file
    volumes:
      - nuxt-data:/app/storage
    networks:
      - warolabs-network

secrets:
  env_file:
    file: .env

networks:
  warolabs-network:
    external: true

volumes:
  nuxt-data:
