/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./components/**/*.{js,vue,ts}",
    "./composables/**/*.{js,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./utils/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./app.vue",
  ],
  safelist: [
    'absolute',
    '-top-1',
    '-end-1',
    'overflow-visible',
    'ring-shell-header-bg',
    'bg-badge-danger-bg',
    'text-badge-danger-text',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
        },
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
        },
        // Warocol Design System Colors - Legacy
        surface: {
          DEFAULT: "hsl(var(--surface) / <alpha-value>)",
          secondary: "hsl(var(--surface-secondary) / <alpha-value>)",
          tertiary: "hsl(var(--surface-tertiary) / <alpha-value>)",
        },
        text: {
          primary: "hsl(var(--text-primary) / <alpha-value>)",
          secondary: "hsl(var(--text-secondary) / <alpha-value>)",
          tertiary: "hsl(var(--text-tertiary) / <alpha-value>)",
        },
        success: {
          DEFAULT: "hsl(var(--success) / <alpha-value>)",
          foreground: "hsl(var(--success-foreground) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "hsl(var(--warning) / <alpha-value>)",
          foreground: "hsl(var(--warning-foreground) / <alpha-value>)",
        },
        info: {
          DEFAULT: "hsl(var(--info) / <alpha-value>)",
          foreground: "hsl(var(--info-foreground) / <alpha-value>)",
        },
        focus: {
          ring: "hsl(var(--focus-ring) / <alpha-value>)",
          subtle: "hsl(var(--focus-ring-subtle) / <alpha-value>)",
        },
        overlay: {
          backdrop: "hsl(var(--overlay-backdrop-bg) / <alpha-value>)",
          "backdrop-subtle": "hsl(var(--overlay-backdrop-subtle-bg) / <alpha-value>)",
          "backdrop-strong": "hsl(var(--overlay-backdrop-strong-bg) / <alpha-value>)",
        },
        modal: {
          "surface-bg": "hsl(var(--modal-surface-bg) / <alpha-value>)",
          "surface-text": "hsl(var(--modal-surface-text) / <alpha-value>)",
          "header-border": "hsl(var(--modal-header-border) / <alpha-value>)",
          "footer-border": "hsl(var(--modal-footer-border) / <alpha-value>)",
        },
        sheet: {
          "surface-bg": "hsl(var(--sheet-surface-bg) / <alpha-value>)",
          "header-bg": "hsl(var(--sheet-header-bg) / <alpha-value>)",
          "footer-bg": "hsl(var(--sheet-footer-bg) / <alpha-value>)",
          border: "hsl(var(--sheet-border) / <alpha-value>)",
        },
        action: {
          primary: {
            bg: "hsl(var(--action-primary-bg) / <alpha-value>)",
            text: "hsl(var(--action-primary-text) / <alpha-value>)",
            border: "hsl(var(--action-primary-border) / <alpha-value>)",
            "hover-bg": "hsl(var(--action-primary-hover-bg) / <alpha-value>)",
            "hover-text": "hsl(var(--action-primary-hover-text) / <alpha-value>)",
            "focus-ring": "hsl(var(--action-primary-focus-ring) / <alpha-value>)",
            "active-bg": "hsl(var(--action-primary-active-bg) / <alpha-value>)",
            "disabled-bg": "hsl(var(--action-primary-disabled-bg) / <alpha-value>)",
            "disabled-text": "hsl(var(--action-primary-disabled-text) / <alpha-value>)",
          },
          secondary: {
            bg: "hsl(var(--action-secondary-bg) / <alpha-value>)",
            text: "hsl(var(--action-secondary-text) / <alpha-value>)",
            border: "hsl(var(--action-secondary-border) / <alpha-value>)",
            "hover-bg": "hsl(var(--action-secondary-hover-bg) / <alpha-value>)",
            "hover-text": "hsl(var(--action-secondary-hover-text) / <alpha-value>)",
            "focus-ring": "hsl(var(--action-secondary-focus-ring) / <alpha-value>)",
            "active-bg": "hsl(var(--action-secondary-active-bg) / <alpha-value>)",
            "disabled-bg": "hsl(var(--action-secondary-disabled-bg) / <alpha-value>)",
            "disabled-text": "hsl(var(--action-secondary-disabled-text) / <alpha-value>)",
          },
          ghost: {
            bg: "hsl(var(--action-ghost-bg) / <alpha-value>)",
            text: "hsl(var(--action-ghost-text) / <alpha-value>)",
            "hover-bg": "hsl(var(--action-ghost-hover-bg) / <alpha-value>)",
            "hover-text": "hsl(var(--action-ghost-hover-text) / <alpha-value>)",
            "focus-ring": "hsl(var(--action-ghost-focus-ring) / <alpha-value>)",
            "active-bg": "hsl(var(--action-ghost-active-bg) / <alpha-value>)",
            "disabled-text": "hsl(var(--action-ghost-disabled-text) / <alpha-value>)",
          },
          outline: {
            bg: "hsl(var(--action-outline-bg) / <alpha-value>)",
            text: "hsl(var(--action-outline-text) / <alpha-value>)",
            border: "hsl(var(--action-outline-border) / <alpha-value>)",
            "hover-bg": "hsl(var(--action-outline-hover-bg) / <alpha-value>)",
            "hover-text": "hsl(var(--action-outline-hover-text) / <alpha-value>)",
            "focus-ring": "hsl(var(--action-outline-focus-ring) / <alpha-value>)",
            "active-bg": "hsl(var(--action-outline-active-bg) / <alpha-value>)",
            "disabled-bg": "hsl(var(--action-outline-disabled-bg) / <alpha-value>)",
            "disabled-text": "hsl(var(--action-outline-disabled-text) / <alpha-value>)",
          },
          destructive: {
            bg: "hsl(var(--action-destructive-bg) / <alpha-value>)",
            text: "hsl(var(--action-destructive-text) / <alpha-value>)",
            border: "hsl(var(--action-destructive-border) / <alpha-value>)",
            "hover-bg": "hsl(var(--action-destructive-hover-bg) / <alpha-value>)",
            "hover-text": "hsl(var(--action-destructive-hover-text) / <alpha-value>)",
            "focus-ring": "hsl(var(--action-destructive-focus-ring) / <alpha-value>)",
            "active-bg": "hsl(var(--action-destructive-active-bg) / <alpha-value>)",
            "disabled-bg": "hsl(var(--action-destructive-disabled-bg) / <alpha-value>)",
            "disabled-text": "hsl(var(--action-destructive-disabled-text) / <alpha-value>)",
          },
          success: {
            bg: "hsl(var(--action-success-bg) / <alpha-value>)",
            text: "hsl(var(--action-success-text) / <alpha-value>)",
            border: "hsl(var(--action-success-border) / <alpha-value>)",
            "hover-bg": "hsl(var(--action-success-hover-bg) / <alpha-value>)",
            "hover-text": "hsl(var(--action-success-hover-text) / <alpha-value>)",
            "focus-ring": "hsl(var(--action-success-focus-ring) / <alpha-value>)",
            "active-bg": "hsl(var(--action-success-active-bg) / <alpha-value>)",
            "disabled-bg": "hsl(var(--action-success-disabled-bg) / <alpha-value>)",
            "disabled-text": "hsl(var(--action-success-disabled-text) / <alpha-value>)",
          },
          warning: {
            bg: "hsl(var(--action-warning-bg) / <alpha-value>)",
            text: "hsl(var(--action-warning-text) / <alpha-value>)",
            border: "hsl(var(--action-warning-border) / <alpha-value>)",
            "hover-bg": "hsl(var(--action-warning-hover-bg) / <alpha-value>)",
            "hover-text": "hsl(var(--action-warning-hover-text) / <alpha-value>)",
            "focus-ring": "hsl(var(--action-warning-focus-ring) / <alpha-value>)",
            "active-bg": "hsl(var(--action-warning-active-bg) / <alpha-value>)",
            "disabled-bg": "hsl(var(--action-warning-disabled-bg) / <alpha-value>)",
            "disabled-text": "hsl(var(--action-warning-disabled-text) / <alpha-value>)",
          },
          info: {
            bg: "hsl(var(--action-info-bg) / <alpha-value>)",
            text: "hsl(var(--action-info-text) / <alpha-value>)",
            border: "hsl(var(--action-info-border) / <alpha-value>)",
            "hover-bg": "hsl(var(--action-info-hover-bg) / <alpha-value>)",
            "hover-text": "hsl(var(--action-info-hover-text) / <alpha-value>)",
            "focus-ring": "hsl(var(--action-info-focus-ring) / <alpha-value>)",
            "active-bg": "hsl(var(--action-info-active-bg) / <alpha-value>)",
            "disabled-bg": "hsl(var(--action-info-disabled-bg) / <alpha-value>)",
            "disabled-text": "hsl(var(--action-info-disabled-text) / <alpha-value>)",
          },
        },
        "icon-button": {
          "neutral-bg": "hsl(var(--icon-button-neutral-bg) / <alpha-value>)",
          "neutral-text": "hsl(var(--icon-button-neutral-text) / <alpha-value>)",
          "neutral-hover-bg": "hsl(var(--icon-button-neutral-hover-bg) / <alpha-value>)",
          "neutral-hover-text": "hsl(var(--icon-button-neutral-hover-text) / <alpha-value>)",
          "primary-bg": "hsl(var(--icon-button-primary-bg) / <alpha-value>)",
          "primary-text": "hsl(var(--icon-button-primary-text) / <alpha-value>)",
          "primary-hover-bg": "hsl(var(--icon-button-primary-hover-bg) / <alpha-value>)",
          "primary-hover-text": "hsl(var(--icon-button-primary-hover-text) / <alpha-value>)",
          "destructive-bg": "hsl(var(--icon-button-destructive-bg) / <alpha-value>)",
          "destructive-text": "hsl(var(--icon-button-destructive-text) / <alpha-value>)",
          "destructive-hover-bg": "hsl(var(--icon-button-destructive-hover-bg) / <alpha-value>)",
          "focus-ring": "hsl(var(--icon-button-focus-ring) / <alpha-value>)",
          "disabled-bg": "hsl(var(--icon-button-disabled-bg) / <alpha-value>)",
          "disabled-text": "hsl(var(--icon-button-disabled-text) / <alpha-value>)",
        },
        "form-control": {
          bg: "hsl(var(--form-control-bg) / <alpha-value>)",
          text: "hsl(var(--form-control-text) / <alpha-value>)",
          border: "hsl(var(--form-control-border) / <alpha-value>)",
          placeholder: "hsl(var(--form-control-placeholder) / <alpha-value>)",
          "focus-border": "hsl(var(--form-control-focus-border) / <alpha-value>)",
          "focus-ring": "hsl(var(--form-control-focus-ring) / <alpha-value>)",
          "disabled-bg": "hsl(var(--form-control-disabled-bg) / <alpha-value>)",
          "disabled-text": "hsl(var(--form-control-disabled-text) / <alpha-value>)",
          help: "hsl(var(--form-help-text) / <alpha-value>)",
          error: "hsl(var(--form-error-text) / <alpha-value>)",
          "error-border": "hsl(var(--form-error-border) / <alpha-value>)",
          "error-ring": "hsl(var(--form-error-ring) / <alpha-value>)",
        },
        shell: {
          "header-bg": "hsl(var(--shell-header-bg) / <alpha-value>)",
          "header-border": "hsl(var(--shell-header-border) / <alpha-value>)",
          "title-text": "hsl(var(--shell-title-text) / <alpha-value>)",
          "subtitle-text": "hsl(var(--shell-subtitle-text) / <alpha-value>)",
          "cta-bg": "hsl(var(--shell-cta-bg) / <alpha-value>)",
          "cta-text": "hsl(var(--shell-cta-text) / <alpha-value>)",
          "cta-hover-bg": "hsl(var(--shell-cta-hover-bg) / <alpha-value>)",
          "cta-focus-ring": "hsl(var(--shell-cta-focus-ring) / <alpha-value>)",
          "action-bg": "hsl(var(--shell-action-bg) / <alpha-value>)",
          "action-text": "hsl(var(--shell-action-text) / <alpha-value>)",
          "action-border": "hsl(var(--shell-action-border) / <alpha-value>)",
          "action-hover-bg": "hsl(var(--shell-action-hover-bg) / <alpha-value>)",
          "action-focus-ring": "hsl(var(--shell-action-focus-ring) / <alpha-value>)",
          "icon-bg": "hsl(var(--shell-icon-bg) / <alpha-value>)",
          "icon-text": "hsl(var(--shell-icon-text) / <alpha-value>)",
          "icon-hover-bg": "hsl(var(--shell-icon-hover-bg) / <alpha-value>)",
          "mobile-bg": "hsl(var(--shell-mobile-bg) / <alpha-value>)",
          "mobile-border": "hsl(var(--shell-mobile-border) / <alpha-value>)",
          "account-bg": "hsl(var(--shell-account-bg) / <alpha-value>)",
          "account-text": "hsl(var(--shell-account-text) / <alpha-value>)",
          "account-hover-bg": "hsl(var(--shell-account-hover-bg) / <alpha-value>)",
          "account-border": "hsl(var(--shell-account-border) / <alpha-value>)",
          "account-indicator-bg": "hsl(var(--shell-account-indicator-bg) / <alpha-value>)",
          "account-icon-text": "hsl(var(--shell-account-icon-text) / <alpha-value>)",
          "account-chevron-text": "hsl(var(--shell-account-chevron-text) / <alpha-value>)",
          "account-avatar-bg": "hsl(var(--shell-account-avatar-bg) / <alpha-value>)",
          "account-avatar-border": "hsl(var(--shell-account-avatar-border) / <alpha-value>)",
          "notification-text": "hsl(var(--shell-notification-text) / <alpha-value>)",
          "notification-muted-text": "hsl(var(--shell-notification-muted-text) / <alpha-value>)",
          "notification-hover-bg": "hsl(var(--shell-notification-hover-bg) / <alpha-value>)",
          "notification-accent": "hsl(var(--shell-notification-accent) / <alpha-value>)",
          "notification-accent-bg": "hsl(var(--shell-notification-accent-bg) / <alpha-value>)",
        },
        badge: {
          "neutral-bg": "hsl(var(--badge-neutral-bg) / <alpha-value>)",
          "neutral-text": "hsl(var(--badge-neutral-text) / <alpha-value>)",
          "neutral-border": "hsl(var(--badge-neutral-border) / <alpha-value>)",
          "neutral-hover-bg": "hsl(var(--badge-neutral-hover-bg) / <alpha-value>)",
          "primary-bg": "hsl(var(--badge-primary-bg) / <alpha-value>)",
          "primary-text": "hsl(var(--badge-primary-text) / <alpha-value>)",
          "primary-border": "hsl(var(--badge-primary-border) / <alpha-value>)",
          "primary-hover-bg": "hsl(var(--badge-primary-hover-bg) / <alpha-value>)",
          "success-bg": "hsl(var(--badge-success-bg) / <alpha-value>)",
          "success-text": "hsl(var(--badge-success-text) / <alpha-value>)",
          "success-border": "hsl(var(--badge-success-border) / <alpha-value>)",
          "warning-bg": "hsl(var(--badge-warning-bg) / <alpha-value>)",
          "warning-text": "hsl(var(--badge-warning-text) / <alpha-value>)",
          "warning-border": "hsl(var(--badge-warning-border) / <alpha-value>)",
          "danger-bg": "hsl(var(--badge-danger-bg) / <alpha-value>)",
          "danger-text": "hsl(var(--badge-danger-text) / <alpha-value>)",
          "danger-border": "hsl(var(--badge-danger-border) / <alpha-value>)",
          "info-bg": "hsl(var(--badge-info-bg) / <alpha-value>)",
          "info-text": "hsl(var(--badge-info-text) / <alpha-value>)",
          "info-border": "hsl(var(--badge-info-border) / <alpha-value>)",
          "profile-bg": "hsl(var(--badge-profile-bg) / <alpha-value>)",
          "profile-text": "hsl(var(--badge-profile-text) / <alpha-value>)",
          "profile-border": "hsl(var(--badge-profile-border) / <alpha-value>)",
          "profile-hover-bg": "hsl(var(--badge-profile-hover-bg) / <alpha-value>)",
        },
        state: {
          danger: {
            bg: "hsl(var(--state-danger-bg) / <alpha-value>)",
            border: "hsl(var(--state-danger-border) / <alpha-value>)",
            text: "hsl(var(--state-danger-text) / <alpha-value>)",
            icon: "hsl(var(--state-danger-icon) / <alpha-value>)",
            action: {
              bg: "hsl(var(--state-danger-action-bg) / <alpha-value>)",
              text: "hsl(var(--state-danger-action-text) / <alpha-value>)",
            },
          },
          warning: {
            bg: "hsl(var(--state-warning-bg) / <alpha-value>)",
            border: "hsl(var(--state-warning-border) / <alpha-value>)",
            text: "hsl(var(--state-warning-text) / <alpha-value>)",
            icon: "hsl(var(--state-warning-icon) / <alpha-value>)",
            action: {
              bg: "hsl(var(--state-warning-action-bg) / <alpha-value>)",
              text: "hsl(var(--state-warning-action-text) / <alpha-value>)",
            },
          },
          success: {
            bg: "hsl(var(--state-success-bg) / <alpha-value>)",
            border: "hsl(var(--state-success-border) / <alpha-value>)",
            text: "hsl(var(--state-success-text) / <alpha-value>)",
            icon: "hsl(var(--state-success-icon) / <alpha-value>)",
            action: {
              bg: "hsl(var(--state-success-action-bg) / <alpha-value>)",
              text: "hsl(var(--state-success-action-text) / <alpha-value>)",
            },
          },
          info: {
            bg: "hsl(var(--state-info-bg) / <alpha-value>)",
            border: "hsl(var(--state-info-border) / <alpha-value>)",
            text: "hsl(var(--state-info-text) / <alpha-value>)",
            icon: "hsl(var(--state-info-icon) / <alpha-value>)",
            action: {
              bg: "hsl(var(--state-info-action-bg) / <alpha-value>)",
              text: "hsl(var(--state-info-action-text) / <alpha-value>)",
            },
          },
        },
        nav: {
          "surface-bg": "hsl(var(--nav-surface-bg) / <alpha-value>)",
          "surface-border": "hsl(var(--nav-surface-border) / <alpha-value>)",
          "item-hover-bg": "hsl(var(--nav-item-hover-bg) / <alpha-value>)",
          "item-active-bg": "hsl(var(--nav-item-active-bg) / <alpha-value>)",
          "icon-idle": "hsl(var(--nav-icon-idle) / <alpha-value>)",
          "icon-hover": "hsl(var(--nav-icon-hover) / <alpha-value>)",
          "icon-active": "hsl(var(--nav-icon-active) / <alpha-value>)",
          "label-idle": "hsl(var(--nav-label-idle) / <alpha-value>)",
          "label-hover": "hsl(var(--nav-label-hover) / <alpha-value>)",
          "label-active": "hsl(var(--nav-label-active) / <alpha-value>)",
          "section-label": "hsl(var(--nav-section-label) / <alpha-value>)",
          divider: "hsl(var(--nav-divider) / <alpha-value>)",
        },
        "data-table": {
          "container-bg": "hsl(var(--data-table-container-bg) / <alpha-value>)",
          "header-bg": "hsl(var(--data-table-header-bg) / <alpha-value>)",
          "header-text": "hsl(var(--data-table-header-text) / <alpha-value>)",
          "row-bg": "hsl(var(--data-table-row-bg) / <alpha-value>)",
          "row-alt-bg": "hsl(var(--data-table-row-alt-bg) / <alpha-value>)",
          "row-hover-bg": "hsl(var(--data-table-row-hover-bg) / <alpha-value>)",
          "row-selected-bg": "hsl(var(--data-table-row-selected-bg) / <alpha-value>)",
          "row-new-bg": "hsl(var(--data-table-row-new-bg) / <alpha-value>)",
          border: "hsl(var(--data-table-border) / <alpha-value>)",
          "cell-text": "hsl(var(--data-table-cell-text) / <alpha-value>)",
          "cell-muted": "hsl(var(--data-table-cell-muted) / <alpha-value>)",
          "footer-bg": "hsl(var(--data-table-footer-bg) / <alpha-value>)",
        },
        control: {
          "toggle-track-off": "hsl(var(--control-toggle-track-off) / <alpha-value>)",
          "toggle-track-on": "hsl(var(--control-toggle-track-on) / <alpha-value>)",
          "toggle-thumb": "hsl(var(--control-toggle-thumb) / <alpha-value>)",
          "toggle-focus-ring": "hsl(var(--control-toggle-focus-ring) / <alpha-value>)",
          "action-hover-bg": "hsl(var(--control-action-hover-bg) / <alpha-value>)",
          "action-hover-text": "hsl(var(--control-action-hover-text) / <alpha-value>)",
        },
        filter: {
          "surface-bg": "hsl(var(--filter-surface-bg) / <alpha-value>)",
          "surface-border": "hsl(var(--filter-surface-border) / <alpha-value>)",
          "control-bg": "hsl(var(--filter-control-bg) / <alpha-value>)",
          "control-text": "hsl(var(--filter-control-text) / <alpha-value>)",
          "control-placeholder": "hsl(var(--filter-control-placeholder) / <alpha-value>)",
          "control-focus-ring": "hsl(var(--filter-control-focus-ring) / <alpha-value>)",
        },
        "status-chip": {
          bg: "hsl(var(--status-chip-bg) / <alpha-value>)",
          text: "hsl(var(--status-chip-text) / <alpha-value>)",
          border: "hsl(var(--status-chip-border) / <alpha-value>)",
        },
        // Status badge tokens — OKLCH perceptually uniform
        // bg: very low chroma (barely tinted) / text: readable contrast
        // Usage: bg-status-critical-bg, text-status-critical-text, etc.
        "status-critical-bg":   "var(--status-critical-bg)",
        "status-critical-text": "var(--status-critical-text)",
        "status-warning-bg":    "var(--status-warning-bg)",
        "status-warning-text":  "var(--status-warning-text)",
        "status-info-bg":       "var(--status-info-bg)",
        "status-info-text":     "var(--status-info-text)",
        "status-success-bg":    "var(--status-success-bg)",
        "status-success-text":  "var(--status-success-text)",
        // Nueva Paleta de Colores - Titan White (Grises Claros)
        titan: {
          50: "hsl(var(--titan-50) / <alpha-value>)",
          100: "hsl(var(--titan-100) / <alpha-value>)",
          200: "hsl(var(--titan-200) / <alpha-value>)",
          300: "hsl(var(--titan-300) / <alpha-value>)",
          400: "hsl(var(--titan-400) / <alpha-value>)",
          500: "hsl(var(--titan-500) / <alpha-value>)",
          600: "hsl(var(--titan-600) / <alpha-value>)",
          700: "hsl(var(--titan-700) / <alpha-value>)",
          800: "hsl(var(--titan-800) / <alpha-value>)",
          900: "hsl(var(--titan-900) / <alpha-value>)",
        },
        // Nueva Paleta de Colores - Crocus Purple (Púrpura)
        crocus: {
          50: "hsl(var(--crocus-50) / <alpha-value>)",
          100: "hsl(var(--crocus-100) / <alpha-value>)",
          200: "hsl(var(--crocus-200) / <alpha-value>)",
          300: "hsl(var(--crocus-300) / <alpha-value>)",
          400: "hsl(var(--crocus-400) / <alpha-value>)",
          500: "hsl(var(--crocus-500) / <alpha-value>)",
          600: "hsl(var(--crocus-600) / <alpha-value>)",
          700: "hsl(var(--crocus-700) / <alpha-value>)",
          800: "hsl(var(--crocus-800) / <alpha-value>)",
          900: "hsl(var(--crocus-900) / <alpha-value>)",
        },
        // Nueva Paleta de Colores - Ebony Clay (Grises Oscuros)
        ebony: {
          50: "hsl(var(--ebony-50) / <alpha-value>)",
          100: "hsl(var(--ebony-100) / <alpha-value>)",
          200: "hsl(var(--ebony-200) / <alpha-value>)",
          300: "hsl(var(--ebony-300) / <alpha-value>)",
          400: "hsl(var(--ebony-400) / <alpha-value>)",
          500: "hsl(var(--ebony-500) / <alpha-value>)",
          600: "hsl(var(--ebony-600) / <alpha-value>)",
          700: "hsl(var(--ebony-700) / <alpha-value>)",
          800: "hsl(var(--ebony-800) / <alpha-value>)",
          900: "hsl(var(--ebony-900) / <alpha-value>)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        principal: ['Lato'],
        sans: ['Lato', 'sans-serif'],
        quantico: ['Quantico', 'Lato', 'sans-serif'],
        display: ['Playfair Display', 'serif'],
        reading: ['Lora', 'Georgia', 'serif'],
        ui: ['Source Sans 3', 'sans-serif'],
      },
      fontSize: {
        "dense-label": [
          "var(--type-dense-label-size)",
          {
            lineHeight: "var(--type-dense-label-line-height)",
            fontWeight: "var(--type-dense-label-weight)",
          },
        ],
        "dense-value": [
          "var(--type-dense-value-size)",
          {
            lineHeight: "var(--type-dense-value-line-height)",
            fontWeight: "var(--type-dense-value-weight)",
          },
        ],
        "dense-meta": [
          "var(--type-dense-meta-size)",
          {
            lineHeight: "var(--type-dense-meta-line-height)",
            fontWeight: "var(--type-dense-meta-weight)",
          },
        ],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require("tailwindcss-animate"),
  ],
}
